spring:
  application:
    name:
      students-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5433/students
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8120
  servlet:
    context-path: /scholarships/api/v1

logging:
  level:
    org:
      hibernate:
        SQL: debug